src/objects/Caliber_Assessment__c.object
<CustomObject>
    <fields>
        <fullName>Assessment_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assessment Category</label>
        <referenceTo>Caliber_Category__c</referenceTo>
        <relationshipLabel>Caliber Assessments</relationshipLabel>
        <relationshipName>Caliber_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Caliber Assessment</label>
    <nameField>
        <displayFormat>ASMNT-{0000000}</displayFormat>
        <label>Caliber Assessment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Caliber Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Caliber_Category__c.object
<CustomObject>
    <description>A record will represent a category that an assessment can fall under. Similar to skills.</description>
    <label>Caliber Category</label>
    <nameField>
        <label>Skill Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Caliber Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TechnicalSkillsApexCon.cls
public class TechnicalSkillsApexCon {
    
    @AuraEnabled
    public static List<Caliber_Assessment__c> getCalCat() {
        List<Caliber_Assessment__c> calCat = new List<Caliber_Assessment__c>();
        calCat = [SELECT Id, Assessment_Category__r.Name FROM Caliber_Assessment__c];
        return calCat;
    }
    
    @AuraEnabled
    public static Training__c getCurrentBatch(Id batchId) {
        return [SELECT Id, TrainingClass__c FROM Training__c WHERE Id = :batchId LIMIT 1];
    }
    
}