src/objects/Caliber_Assessment__c.object
<CustomObject>
    <fields>
        <fullName>Assessment_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assessment Category</label>
        <referenceTo>Caliber_Category__c</referenceTo>
        <relationshipLabel>Caliber Assessments</relationshipLabel>
        <relationshipName>Caliber_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assessment_Type__c</fullName>
        <label>Assessment Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Exam</fullName>
                </value>
                <value>
                    <fullName>Verbal</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Presentation</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Max_Points__c</fullName>
        <description>An arbitrary number designating the maximum number of points a trainee can earn for an assessment. The weighted score (out of 100%) is determined by Caliber_Grade__c.Score__c / Max_Points__c</description>
        <label>Max Points</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Training_Id__c</fullName>
        <label>Training Id</label>
        <referenceTo>Training__c</referenceTo>
        <relationshipLabel>Caliber Assessments</relationshipLabel>
        <relationshipName>Caliber_Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Week_Number__c</fullName>
        <description>The week that the test was administered, for example a Java Verbal test on Week 1.</description>
        <label>Week Number</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Caliber Assessment</label>
    <nameField>
        <displayFormat>ASMNT-{0000000}</displayFormat>
        <label>Caliber Assessment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Caliber Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Caliber_Category__c.object
<CustomObject>
    <description>A record will represent a category that an assessment can fall under. Similar to skills.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Caliber Category</label>
    <nameField>
        <label>Skill Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Caliber Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Caliber_Grade__c.object
<CustomObject>
    <fields>
        <fullName>Caliber_Assessment__c</fullName>
        <label>Caliber Assessment</label>
        <referenceTo>Caliber_Assessment__c</referenceTo>
        <relationshipLabel>Caliber Grades</relationshipLabel>
        <relationshipName>Caliber_Grades</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Caliber Grades</relationshipLabel>
        <relationshipName>Caliber_Grades</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <description>The actual number of raw points earned by the trainee for the assessment. Trainers typically enter a percentage on the UI such as 85.4%, but the score is transformed to the weighted score, for example (Max_Points__c * 0.854)</description>
        <label>Score</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Caliber Grade</label>
    <nameField>
        <displayFormat>GRD-{0000000}</displayFormat>
        <label>Caliber Grade Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Caliber Grades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Caliber_Note__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Caliber Notes</relationshipLabel>
        <relationshipName>Caliber_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_QC_Feedback__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this box is Checked that indicates that this note is QC feedback.</description>
        <label>Is QC Feedback</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Note_Content__c</fullName>
        <label>Note Content</label>
        <length>100000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Note_Type__c</fullName>
        <label>Note Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Trainee</fullName>
                </value>
                <value>
                    <fullName>Batch</fullName>
                </value>
                <value>
                    <fullName>QC Trainee</fullName>
                </value>
                <value>
                    <fullName>QC Batch</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>QC_Status__c</fullName>
        <label>QC Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Undefined</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Superstar</fullName>
                </value>
                <value>
                    <fullName>Good</fullName>
                </value>
                <value>
                    <fullName>Average</fullName>
                </value>
                <value>
                    <fullName>Poor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Training__c</fullName>
        <label>Training</label>
        <referenceTo>Training__c</referenceTo>
        <relationshipLabel>Caliber Notes</relationshipLabel>
        <relationshipName>Caliber_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Week_Number__c</fullName>
        <label>Week Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Caliber Note</label>
    <nameField>
        <displayFormat>Note-{0000000}</displayFormat>
        <label>Caliber Note Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Caliber Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Master_Stage__c</fullName>
        <label>Master Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Career Coach</fullName>
                </value>
                <value>
                    <fullName>Not Considering</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Qualifying</fullName>
                </value>
                <value>
                    <fullName>Recruitment</fullName>
                </value>
                <value>
                    <fullName>Screening</fullName>
                </value>
                <value>
                    <fullName>Selected</fullName>
                </value>
                <value>
                    <fullName>Staging</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BatchCreation.cls
public class BatchCreation {
    
    /* Set the trainerId to a user Id for a user that will be considered a trainer */
    public static Id trainerId = UserInfo.getUserId();
    
    
    public static List<String> firstNames = new List<String>{'Donald', 'Mickey', 'Daisy', 'Goofy', 'Minnie', 'Dan', 'Oliver', 'Barry', 'Felicity', 'Iris', 
        'Kaitlin', 'Cisco', 'John', 'Nora', 'Iobard', 'Matthew', 'Jessica', 'Foggy', 'Karen', 'Luke'};
    public static List<String> lastNames = new List<String>{'Duck', 'Mouse', 'Duck', 'Goofy', 'Mouse', 'Pickles', 'Queen', 'Allen', 'Smoak', 'West-Allen', 
        'Snow', 'Ramone', 'Diggle', 'Allen', 'Thon', 'Murdock', 'Jones', 'Nelson', 'Paige', 'Cage'};
            
    public static void createData(){
        //Creates 20 associates
        List<Contact> associates = new List<Contact>();
        for(Integer i = 0; i < 20; i++){
            Contact a = new Contact();
            a.Email = firstNames[i] + lastNames[i] + '@test.com';
            a.Master_Stage__c = 'Training';
            a.FirstName = firstNames[i];
            a.LastName = lastNames[i];
            associates.add(a);
        }
        insert associates;
    
        //create Training_Track
        Training_Track__c track = new Training_Track__c();
        track.Active__c = true;
        track.ShortName__c = 'Salesforce';
        track.Name = 'Salesforce';
        insert track; 
        
        //Create batch
        Training__c batch = new Training__c();
        batch.StartDate__c = Date.parse('09/10/2018');
        batch.EndDate__c = Date.parse('11/16/2018');
        batch.Status__c = 'In Progress';
        batch.Trainer__c = trainerId;
        batch.TrainingTrack__c = track.Id;
        insert batch;
        
        //Create Training Assignments
        List<Training_Assignment__c> taList = new List<Training_Assignment__c>();
        for(Integer i = 0; i < 20; i++){
            Training_Assignment__c ta = new Training_Assignment__c();
            ta.Contact__c = associates[i].Id;
            ta.Training__c = batch.Id;
            ta.Name = 'TA-00' + i;
            taList.add(ta);
        }
        insert taList;
        
        //create Assessments and grades
        createAssessmentAndGrades(batch.Id, associates);
        
    }//end of Create Data
    
    public static void createAssessmentAndGrades(Id trainingId, List<Contact> associates){
        //create categories for assessments
        List<Caliber_Category__c> cats = new List<Caliber_Category__c>();
        List<String> catNames = new List<String>{'SF Security', 'SF Data Model', 'Sales Cloud', 'Apex', 'Visualforce'};
        for(Integer i = 0; i < 5; i++){
            Caliber_Category__c cat = new Caliber_Category__c();
            cat.Active__c = true;
            cat.Name = catNames[i];
            cats.add(cat);
        }
        insert cats;
        
        //create assessments
        List<Caliber_Assessment__c> assessmentList = new List<Caliber_Assessment__c>();
        for(Integer i = 1; i < 6; i++){
            Caliber_Assessment__c assessment = new Caliber_Assessment__c();
            assessment.Assessment_Type__c = 'Exam';
            assessment.Max_Points__c = 100;
            assessment.Training_Id__c = trainingId;
            assessment.Week_Number__c = i;
            assessment.Assessment_Category__c = cats[i-1].Id;
            assessmentList.add(assessment);
        }
        insert assessmentList;
        
        //create grades for assessments
        List<Caliber_Grade__c> grades = new List<Caliber_Grade__c>();
        ////iterate through assessments
        for(Integer i = 0; i < 5; i++){
            //iterate through associates
            for(Integer j = 0; j < 20; j++){
                Caliber_Grade__c g = new Caliber_Grade__c();
                g.Caliber_Assessment__c = assessmentList[i].Id;
                g.Contact__c = associates[j].Id;
                g.Score__c = (10*i) + 50;
                grades.add(g);
            }
        }
        insert grades;
        
        List<Caliber_Note__c> qcList = new List<Caliber_Note__c>();
        //iterate through weeks
        for (Integer i = 1; i < 6; i++){
            Caliber_Note__c b = new Caliber_Note__c();
            b.Is_QC_Feedback__c = true;
            b.Note_Type__c = 'QC Batch';
            b.QC_Status__c = 'Good';
            b.Training__c = trainingId;
            b.Week_Number__c = i;
            b.Note_Content__c = 'good job on week ' + i;
            qcList.add(b);
            //iterate through associates
            for (Integer j = 0; j < 20; j++){
                Caliber_Note__c n = new Caliber_Note__c();
                n.Contact__c = associates[j].Id;
                n.Is_QC_Feedback__c = true;
                n.Note_Type__c = 'QC Trainee';
                n.QC_Status__c = 'Good';
                n.Training__c = trainingId;
                n.Week_Number__c = i;
                n.Note_Content__c = 'good job on week ' + i;
                qcList.add(n);
            }
        }
        insert qcList;
        
    }//end of createAssessmentAndGrades
    
    public static void reCreateData(){
    	delete [SELECT Id FROM Caliber_Note__c];
		delete [SELECT Id FROM Caliber_Grade__c];
		delete [SELECT Id FROM Caliber_Assessment__c];
		delete [SELECT Id FROM Caliber_Category__c];
		delete [SELECT Id FROM Training_Assignment__c];
		delete [SELECT Id FROM Training__c];
		delete [SELECT Id FROM Training_Track__c];
		Database.delete([SELECT Id FROM Contact], false);
		BatchCreation.createData();
    }
}//end of class